routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('users', 'Admin\\UserController');
    Route::resource('revendas', 'Admin\\RevendaController');
    Route::resource('bouquets', 'Admin\\BouquetController');
    Route::resource('categories', 'Admin\\CategoryController');
    Route::resource('streams', 'Admin\\StreamController');
    Route::resource('radios', 'Admin\\RadioController');
    Route::resource('epg', 'Admin\\EpgController');
    Route::resource('hosts', 'Admin\\HostController');
    Route::resource('movies', 'Admin\\MovieController');
    Route::resource('collections', 'Admin\\CollectionController');
    Route::resource('series', 'Admin\\SerieController');
    Route::resource('seasons', 'Admin\\SeasonController');
    Route::resource('episodes', 'Admin\\EpisodeController');

    Route::get('audits', 'AuditController@index');
    Route::post('/revendas/password/?', 'Admin\\RevendaController@password');
});

Route::get('job', 'HomeController@job');
Route::get('card', 'HomeController@card');
Route::get('csv', 'HomeController@csv');
Route::get('screen', 'HomeController@homescreen');
Route::get('teste', 'HomeController@teste');

//Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

app/Radio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Contracts\Auditable;

class Radio extends Model implements Auditable
{
    use  \OwenIt\Auditing\Auditable, SoftDeletes;

    protected $fillable = [
        'name',
        'category_id',
        'epg_id',
        'stream_logo',
        'stream_link',
        'status',
        'notes',
    ];

    public function bouquets() {
        return $this->hasMany(BouquetRelation::class, 'resource_id', 'id');
    }

    public function available_bouquets() {
        return $this->bouquets()->where('resource', '=', 'radio');
    }
}

app/Http/Controllers/Admin/RadioController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Bouquet;
use App\BouquetRelation;
use App\Category;
use App\Http\Controllers\Controller;
use App\Radio;
use App\Stream;
use App\TvSerieSeason;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RadioController extends Controller
{

    private $categories;
    private $bouquets;

    public function __construct()
    {
        $categories = Category::where('status', 1)->get();
        $categories = $categories->toArray();

        $bouquets = Bouquet::where('status', 1)->get();
        $bouquets = $bouquets->toArray();

        $this->categories =  parseSelectArray($categories, 'name');
        $this->bouquets =  parseSelectArray($bouquets, 'name');;
    }

    public function index()
    {
        $radios = Radio::all();
        return view('radios.index')->with(compact('radios'));
    }

    public function create()
    {
        $categories = $this->categories;
        $bouquets = $this->bouquets;

        return view('radios.create')->with(compact('categories', 'bouquets'));
    }

    public function store(Request $request) {

        $request->validate([
            'name' => 'required',
            'stream_logo' => 'required|mimes:jpeg,bmp,png,jpg',
            'stream_link' => 'required|url',
            'category_id' => 'required|exists:categories,id'
        ]);

        $data = $request->all();

        if($request->hasFile('stream_logo')) {
            $image = $request->file('stream_logo');
            $imageName = time() . '.' . $image->getClientOriginalExtension();
            $destinationPath = public_path('/img/radio/');
            $image->move($destinationPath, $imageName);
            $image->imagePath = $destinationPath . $imageName;
            $data['stream_logo'] = url('img/radio/' . $imageName);
        }

        $radio = Radio::create($data);
        if($radio && isset($data['bouquet_id'])) {
            foreach ($data['bouquet_id'] as $bouquet){
                BouquetRelation::create(['resource_id' => $radio->id, 'resource' => 'stream', 'bouquet_id'=>$bouquet]);
            }
        }

        return redirect()->route('radios.index')->with('success', __('messages.radios.created'));
    }

    public function edit($id)
    {
        $categories = $this->categories;
        $bouquets = $this->bouquets;

        $radio = Radio::findOrFail($id);
        return view('radios.edit')->with(compact('radio', 'categories', 'bouquets'));
    }

    public function update(Request $request, $id) {

        $validate = [
            'name' => 'required',
            'stream_logo' => 'mimes:jpeg,bmp,png,jpg',
            'stream_link' => 'required|url',
            'category_id' => 'required|exists:categories,id'
        ];

        if(empty($request->get('stream_logo')))
            unset($validate['stream_logo']);

        $request->validate($validate);

        $data = $request->all();

        if(empty($request->get('stream_logo')))
            unset($data['stream_logo']);

        if($request->hasFile('stream_logo')) {
            $image = $request->file('stream_logo');
            $imageName = time() . '.' . $image->getClientOriginalExtension();
            $destinationPath = public_path('/img/radio/');
            $image->move($destinationPath, $imageName);
            $image->imagePath = $destinationPath . $imageName;
            $data['stream_logo'] = url('img/radio/' . $imageName);
        }

        $radio = Radio::find($id);
        $radio->update($data);
        $radio->save();

        if($radio){
            $relation = BouquetRelation::where(['resource_id' => $radio->id, 'resource' => 'stream']);
            if($relation->count()) {
                $relation->delete();
            }

            if(isset($data['bouquet_id'])) {
                foreach ($data['bouquet_id'] as $bouquet){
                    BouquetRelation::create(['resource_id' => $radio->id, 'resource' => 'stream', 'bouquet_id'=>$bouquet]);
                }
            }

        }


        return redirect()->route('radios.index')->with('success', __('messages.radios.updated'));
    }

    public function destroy($id) {
        $radio = Radio::findOrFail($id);

        if($radio) {
            $radio->deleted_by = Auth::user()->id;
            $radio->delete();
            $radio->save();
            return redirect()->route('radios.index')->with('success', __('messages.radios.deleted'));
        }
        return redirect()->route('radios.index')->with('error', __('messages.radios.not_found'));

    }
}

resources/views/radios/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="element-wrapper">
                <div class="element-actions">
                    <a href="{{ route('radios.index') }}" type="button" class="btn btn-outline-secondary min-width-125 pull-right">Voltar</a>
                </div>
                <h6 class="element-header">
                    Cadastro de Radio
                </h6>
                <div class="element-content">
                    <div class="element-box">
                        {!!  Form::open(['route' => ['radios.store'], 'enctype' => 'multipart/form-data']) !!}

                            @csrf
                            @method('POST')

                            <x-input name="name" text="Nome" placeholder="Digite o Nome da Stream" :error="$errors"/>

                            <x-input-prepend prepend="http://" name="stream_link" text="Stream URL" placeholder="Insira a URL da Stream" :error="$errors"/>

                            <x-select2 name="category_id" text="Categoria" placeholder="Selecione a Categoria" :error="$errors"
                                       :options="$categories"/>

                            <x-multiselect name="bouquet_id[]" text="Bouquets" placeholder="Selecione o(s) Bouquet(s)" :error="$errors"
                                       :options="$bouquets"/>

                            <x-input-file name="stream_logo" text="Stream Logo" placeholder="" :error="$errors"/>

                            <x-text-area name="notes" text="Observação" placeholder="Digite o texto" :error="$errors"/>

                            <button type="submit" class="btn btn-primary min-width-125">Cadastrar</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/radios/edit.blade.php
@extends('layouts.app')

@section('content')
    <x-message :message="Session::has('success') ? Session::get('success') : ''"/>

    <div class="row">
        <div class="col-lg-6">
            <div class="element-wrapper">
                <div class="element-actions">
                    <a href="{{ route('radios.index') }}" type="button" class="btn btn-outline-secondary min-width-125 pull-right">Voltar</a>
                </div>
                <h6 class="element-header">
                    Edição de Radio
                </h6>

                <div class="element-content">
                    <div class="element-box">
                        {!!  Form::model($stream, ['method' => 'PUT','route' => ['radios.update', $radio->id],  'enctype' => 'multipart/form-data']) !!}
                        @csrf

                        @csrf
                        @method('PUT')

                        <x-input name="name" text="Nome" :value="$stream->name" placeholder="Digite o Nome da Stream" :error="$errors"/>

                        <x-input-prepend prepend="http://" :value="$stream->stream_link" name="stream_link" text="Stream URL" placeholder="Insira a URL da Stream" :error="$errors"/>

                        <x-select2 name="category_id" text="Categoria" :value="$stream->category_id" placeholder="Selecione a Categoria" :error="$errors"
                                   :options="$categories"/>

                        <x-multiselect name="bouquet_id[]" text="Bouquets" :value="$stream->available_bouquets" placeholder="Selecione o(s) Bouquet(s)" :error="$errors"
                                       :options="$bouquets"/>

                        <x-input-file name="stream_logo" text="Stream Logo" placeholder="" :error="$errors"/>

                        <x-text-area name="notes" text="Observação" :value="$stream->notes" placeholder="Digite o texto" :error="$errors"/>

                        <button type="submit" class="btn btn-primary min-width-125">Salvar</button>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/radios/index.blade.php
@extends('layouts.app')

@section('content')
    <x-message :message="Session::has('success') ? Session::get('success') : ''"/>

    <div class="element-wrapper">
        <div class="element-actions">
            <a href="{{ route('radios.create') }}" type="button" class="btn btn-primary min-width-125 pull-right">Cadastrar Radio</a>
        </div>
        <h6 class="element-header">
            Gerenciar Radio
        </h6>

        <div class="element-content">
            <table id="dataTable1" class="table table-bordered table-striped table-vcenter js-dataTable-full">
                <thead>
                <tr>
                    <th class="text-center"></th>
                    <th class="text-center">Logo</th>
                    <th class="text-center">Nome</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Status</th>
                    <th class="text-center" style="width: 15%;"></th>
                </tr>
                </thead>
                <tbody>
                    @foreach($radios as $radio)
                        <tr>
                            <td class="text-center" style="width: 5%">{{ $radio->id }}</td>
                            <td class="text-center" style="width: 5%">
                                <x-image-cell :url="$radio->stream_logo"/>
                            </td>
                            <td class="text-center">{{ $radio->name }}</td>
                            <td class="text-center">
                                <x-status-table :status="$radio->status"/>
                            </td>
                            <td class="text-center">
                                <x-button :route="route('streams.edit', $radio->id)" type="info" icon="os-icon-edit-32" tooltip="Editar Bouquet" />
                                <button type="button" class="btn btn-danger" data-toggle="tooltip" title="Deletar" onclick="deletResource({{$radio->id}})">
                                    <i class="os-icon os-icon-trash-2"></i>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>


@endsection


@section('after-script')

    <form action="" id="id-form-delete" method="POST" style="display: none">
        @method('DELETE')
        @csrf
    </form>

    <script>
        @if(Session::has('success'))
        Swal.fire(
            'Suecesso!',
            '{{Session::get('success')}}',
            'success'
        );
        @endif
        function deletResource(id) {
            Swal.fire({
                title: 'Tem certeza?',
                text: "O Recurso será deletado da base",
                icon: 'warning',
                showCancelButton: true,
                cancelButtonText: "Cancelar",
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sim Deletar'
            }).then((result) => {
                if (result.value) {
                    $("#id-form-delete").attr('action', '/radios/' + id);
                    $("#form-status").val(status);
                    $("#id-form-delete").submit();
                }
            })
        }
    </script>
@endsection