routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('users', 'Admin\\UserController');
    Route::resource('revendas', 'Admin\\RevendaController');
    Route::resource('bouquets', 'Admin\\BouquetController');
    Route::resource('categories', 'Admin\\CategoryController');
    Route::resource('streams', 'Admin\\StreamController');
    Route::resource('radios', 'Admin\\RadioController');
    Route::resource('epg', 'Admin\\EpgController');
    Route::resource('hosts', 'Admin\\HostController');
    Route::resource('movies', 'Admin\\MovieController');
    Route::resource('collections', 'Admin\\CollectionController');
    Route::resource('series', 'Admin\\SerieController');
    Route::resource('seasons', 'Admin\\SeasonController');
    Route::resource('episodes', 'Admin\\EpisodeController');

    Route::get('audits', 'AuditController@index');
    Route::post('/revendas/password/?', 'Admin\\RevendaController@password');
});

Route::get('job', 'HomeController@job');
Route::get('card', 'HomeController@card');
Route::get('csv', 'HomeController@csv');
Route::get('screen', 'HomeController@homescreen');
Route::get('teste', 'HomeController@teste');

//Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

resources/views/movies/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="element-wrapper">
                <div class="element-actions">
                    <a href="{{ route('movies.index') }}" type="button" class="btn btn-outline-secondary min-width-125 pull-right">Voltar</a>
                </div>
                <h6 class="element-header">
                    Cadastro de Filmes
                </h6>
                <div class="element-content">
                    <div class="element-box">
                        {!!  Form::open(['route' => ['movies.store']]) !!}
                            @csrf

                            <x-input name="title" text="Título" placeholder="Digite o Titulo do Filme" :error="$errors"/>

                            <x-input name="tmdb_id" text="TMDB ID" placeholder="ID do Filme no TMDB" :error="$errors"/>

                            <x-multiselect name="bouquet_id[]" text="Bouquets" placeholder="Selecione o(s) Bouquet(s)" :error="$errors"
                                           :options="$bouquets"/>

                            <x-select2 name="category_id" text="Categoria" placeholder="Selecione a Categoria" :error="$errors"
                                       :options="$categories"/>

                            <x-input-prepend prepend="http://" name="movie_link" text="Filme URL" placeholder="Insira a URL do Filme" :error="$errors"/>

                            <button type="submit" class="btn btn-primary min-width-125">Cadastrar</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/movies/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="element-wrapper">
                <div class="element-actions">
                    <a href="{{ route('movies.index') }}" type="button" class="btn btn-outline-secondary min-width-125 pull-right">Voltar</a>
                </div>
                <h6 class="element-header">
                    Edição de Filmes
                </h6>
                <div class="element-content">
                    <div class="element-box">
                        {!!  Form::model($movie, ['method' => 'PUT','route' => ['movies.update', $movie->id], 'enctype' => 'multipart/form-data']) !!}
                        @csrf

                        <x-input name="tmdb_id" text="TMDB ID" :value="$movie->tmdb_id" placeholder="TMDB ID" :error="$errors"/>

                        <x-input name="title" text="Título" :value="$movie->title" placeholder="Digite o Titulo" :error="$errors"/>

                        <x-select2 name="category_id" text="Categoria" :value="$movie->category_id" placeholder="Selecione a Categoria" :error="$errors"
                                   :options="$categories"/>


                        <x-multiselect name="bouquet_id[]" text="Bouquets" :value="$movie->available_bouquets" placeholder="Selecione o(s) Bouquet(s)" :error="$errors"
                                       :options="$bouquets"/>

                        <x-select2 name="collection_id" text="Collection" :value="$movie->collection_id" placeholder="Selecione a Collection" :error="$errors"
                                   :options="$collections"/>

                        <x-input name="movie_link" text="Link do Filme" :value="$movie->movie_link" placeholder="Digite Link do Filme" :error="$errors"/>

                        <x-input name="trailer_url" text="Trailer do Filme" :value="$movie->trailer_url" placeholder="Digite Trailer do Filme" :error="$errors"/>

                        <x-input type="number" name="rating" text="Avaliação" :value="$movie->rating" placeholder="Digite a Avaliação do Filme" :error="$errors"/>

                        <x-input name="released" text="Lançamento" :value="$movie->released" placeholder="Data de Lançamento" :error="$errors"/>

                        <x-text-area name="detail" text="Overview" :value="$movie->detail" placeholder="Digite o texto" :error="$errors"/>

                        <h6><b>Thumbnail</b></h6>
                        <div class="profile-tile">
                            <a class="profile-tile-box" href="{{ $movie->thumbnail }}" target="_blank">
                                <div class="pt-avatar-w">
                                    <img alt="" src="{{ $movie->thumbnail }}">
                                </div>
                            </a>
                            <div class="pt-btn">
                                <button type="button" class="btn btn-secondary btn-sm" onclick="$('#thumbnail').trigger('click');">Alterar</button>
                            </div>
                        </div>
                        <x-input-file display="none" name="thumbnail" text="" placeholder="" :error="$errors"/>

                        <h6><b>Poster</b></h6>
                        <div class="profile-tile">
                            <a class="profile-tile-box" href="{{ $movie->poster }}" target="_blank">
                                <div class="pt-avatar-w">
                                    <img alt="" src="{{ $movie->poster }}">
                                </div>
                            </a>
                            <div class="pt-btn">
                                <button type="button" class="btn btn-secondary btn-sm" onclick="$('#poster').trigger('click');">Alterar</button>
                            </div>
                        </div>

                        <x-input-file display="none" name="poster" text="" placeholder="" :error="$errors"/>



                        <button type="submit" class="btn btn-primary min-width-125">Salvar</button>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/movies/index.blade.php
@extends('layouts.app')


@section('content')

    <div class="element-wrapper">
        <div class="element-actions">
            <a href="{{ route('movies.create') }}" type="button" class="btn btn-primary min-width-125 pull-right">Cadastrar Filmes</a>
        </div>
        <h6 class="element-header">
            Gerenciar Filmes
        </h6>
        <div class="element-content">
            <table id="dataTable1" class="table table-bordered table-striped table-vcenter js-dataTable-full">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">TMDB</th>
                    <th class="text-center">Thumbail</th>
                    <th class="text-center">Poster</th>
                    <th class="text-center">Nome</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Coleção</th>
                    <th class="text-center"></th>
                </tr>
                </thead>
                <tbody>
                    @foreach($movies as $movie)
                        <tr>

                            <td class="text-center">{{ $movie->id }}</td>
                            <td class="text-center">{{ $movie->tmdb_id }}</td>
                            <td class="text-center">
                                <x-image-cell :url="$movie->thumbnail"/>
                            </td>
                            <td class="text-center">
                                <x-image-cell :url="$movie->poster"/>
                            </td>
                            <td class="text-center">{{ $movie->title }}</td>
                            <td class="text-center">
                                @if($movie->status === 'online')
                                    <x-bedge type="success" text="Online" />
                                @elseif($movie->status === 'offline')
                                    <x-bedge type="warning" text="Offline" />
                                @else
                                    <x-bedge type="danger" :text="$movie->status" />
                                @endif
                            </td>
                            <td class="text-center">
                                @if(!empty($movie->collection_id))
                                <a href="{{ route('collections.show', $movie->collection_id) }}">
                                    {{ $movie->collection->name ?? '' }}
                                </a>
                                @else
                                    n/a
                                @endif
                            </td>
                            <td>
                                <x-button :route="route('movies.edit', $movie->id)" type="info" icon="os-icon-film" tooltip="Editar Filme" />
                                @if($movie->status == 'pending-aprove' || $movie->status == 'offline')
                                    <button type="button" class="btn btn-success" data-toggle="tooltip"  title="Alterar par Online" onclick="setStatusMovie('online', {{$movie->id}})">
                                        <i class="os-icon os-icon-video"></i>
                                    </button>
                                @else
                                    <button type="button" class="btn btn-warning" data-toggle="tooltip"  title="Alterar par Offline" onclick="setStatusMovie('offline', {{$movie->id}})">
                                        <i class="os-icon os-icon-video-off"></i>
                                    </button>
                                @endif
                                <button type="button" class="btn btn-danger" data-toggle="tooltip"  title="Deletar" onclick="deleteMovie({{$movie->id}})">
                                    <i class="os-icon os-icon-x"></i>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <form action="" id="id-form" method="POST" style="display: none">
        @method('PUT')
        @csrf
        <input type="text" value="online" name="status" id="form-status">
    </form>
    <form action="" id="id-form-delete" method="POST" style="display: none">
        @method('DELETE')
        @csrf
    </form>
@endsection


@section('after-script')
    <script>
        @if(Session::has('success'))
            Swal.fire(
                'Suecesso!',
                '{{Session::get('success')}}',
                'success'
            );
        @endif
        function setStatusMovie(status, id) {
            Swal.fire({
                title: 'Tem certeza?',
                text: "Você esta alterando este filme para " + status,
                icon: 'warning',
                showCancelButton: true,
                cancelButtonText: "Cancelar",
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sim Alterar'
            }).then((result) => {
                if (result.value) {
                    $("#id-form").attr('action', '/movies/' + id);
                    $("#form-status").val(status);
                    $("#id-form").submit();
                }
            })
        }
        function deleteMovie(id) {
            Swal.fire({
                title: 'Tem certeza?',
                text: "O Filme será deletado da base",
                icon: 'warning',
                showCancelButton: true,
                cancelButtonText: "Cancelar",
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sim Deletar'
            }).then((result) => {
                if (result.value) {
                    $("#id-form-delete").attr('action', '/movies/' + id);
                    $("#form-status").val(status);
                    $("#id-form-delete").submit();
                }
            })
        }
    </script>
@endsection