routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('users', 'Admin\\UserController');
    Route::resource('revendas', 'Admin\\RevendaController');
    Route::resource('bouquets', 'Admin\\BouquetController');
    Route::resource('categories', 'Admin\\CategoryController');
    Route::resource('streams', 'Admin\\StreamController');
    Route::resource('radios', 'Admin\\RadioController');
    Route::resource('epg', 'Admin\\EpgController');
    Route::resource('hosts', 'Admin\\HostController');
    Route::resource('movies', 'Admin\\MovieController');
    Route::resource('collections', 'Admin\\CollectionController');
    Route::resource('series', 'Admin\\SerieController');
    Route::resource('seasons', 'Admin\\SeasonController');
    Route::resource('episodes', 'Admin\\EpisodeController');

    Route::get('audits', 'AuditController@index');
    Route::post('/revendas/password/?', 'Admin\\RevendaController@password');
});

Route::get('job', 'HomeController@job');
Route::get('card', 'HomeController@card');
Route::get('csv', 'HomeController@csv');
Route::get('screen', 'HomeController@homescreen');
Route::get('teste', 'HomeController@teste');

//Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

resources/views/series/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="element-wrapper">
                <div class="element-actions">
                    <a href="{{ route('series.index') }}" type="button" class="btn btn-outline-secondary min-width-125 pull-right">Voltar</a>
                </div>
                <h6 class="element-header">
                    Cadastro de Séries de TV
                </h6>

                <div class="element-content">
                    <div class="element-box">
                        {!!  Form::open(['route' => ['series.store'], 'enctype' => 'multipart/form-data']) !!}
                            @csrf

                            <x-input name="title" text="Título" placeholder="Digite o Título" :error="$errors"/>
                        
                            <x-input name="tmdb_id" text="TMDB ID" placeholder="Digite o TMDB ID" :error="$errors"/>

                            <x-multiselect name="bouquet_id[]" text="Bouquets" placeholder="Selecione o(s) Bouquet(s)" :error="$errors"
                                           :options="$bouquets"/>

                            <x-text-area name="detail" text="Overview" placeholder="Digite o texto" :error="$errors"/>

                            <x-input type="number" name="rating" text="Rating" placeholder="Digite o Título" :error="$errors"/>

                            <x-input-file name="poster_path" text="Poster" placeholder="" :error="$errors"/>

                        <button type="submit" class="btn btn-primary min-width-125">Cadastrar</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/series/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="element-wrapper">
                <div class="element-actions">
                    <a href="{{ route('series.index') }}" type="button" class="btn btn-outline-secondary min-width-125 pull-right">Voltar</a>
                </div>
                <h6 class="element-header">
                    Edição de Séries de TV
                </h6>

                <div class="element-content">
                    <div class="element-box">
                        {!!  Form::model($serie, ['method' => 'PUT','route' => ['series.update', $serie->id], 'enctype' => 'multipart/form-data']) !!}
                        @csrf

                        <x-input name="title" text="Título" :value="$serie->title" placeholder="Digite o Título" :error="$errors"/>
                        <x-input name="tmdb_id" text="TMDB ID" :value="$serie->tmdb_id" placeholder="Digite o TMDB ID" :error="$errors"/>

                        <x-multiselect name="bouquet_id[]" text="Bouquets" :value="$serie->available_bouquets" placeholder="Selecione o(s) Bouquet(s)" :error="$errors"
                                       :options="$bouquets"/>

                        <x-text-area name="detail" text="Overview" :value="$serie->detail" placeholder="Digite o texto" :error="$errors"/>


                        <x-input type="number" name="rating" text="Rating" :value="$serie->rating" placeholder="Digite o Título" :error="$errors"/>

                        <h6><b>Poster</b></h6>
                        <div class="profile-tile">
                            <a class="profile-tile-box" href="{{ $serie->poster_path }}" target="_blank">
                                <div class="pt-avatar-w">
                                    <img alt="" src="{{ $serie->poster_path }}">
                                </div>
                            </a>
                            <div class="pt-btn">
                                <button type="button" class="btn btn-secondary btn-sm" onclick="$('#poster_path').trigger('click');">Alterar</button>
                            </div>
                        </div>
                        <x-input-file display="none" name="poster_path" text="" placeholder="" :error="$errors"/>

                        <button type="submit" class="btn btn-primary min-width-125">Salvar</button>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/series/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="element-wrapper">
        <div class="element-actions">
            <a href="{{ route('series.create') }}" type="button" class="btn btn-primary min-width-125 pull-right">Cadastrar Séries e TV</a>
        </div>
        <h6 class="element-header">
            Gerenciar Séries e TV
        </h6>

        <div class="element-content">
            <table id="dataTable1" class="table table-bordered table-striped table-vcenter js-dataTable-full">
                <thead>
                <tr>
                    <th class="text-center"></th>
                    <th class="text-center">Titulo</th>
                    <th>Poster</th>
                    <th class="d-none d-sm-table-cell">Rating</th>
                    <th class="text-center" style="width: 15%;"></th>
                </tr>
                </thead>
                <tbody>
                    @foreach($series as $serie)
                        <tr>
                            <td class="text-center">{{ $serie->id }}</td>
                            <td class="text-center">{{ $serie->title }}</td>
                            <td class="text-center">
                                <x-image-cell :url="$serie->poster_path"/>
                            </td>
                            <td>{{$serie->rating}}</td>
                            <td class="text-center">
                                <x-button :route="route('series.edit', $serie->id)" type="info" icon="os-icon-edit" tooltip="Editar Series" />
                                <button type="button" class="btn btn-danger" data-toggle="tooltip" title="Deletar" onclick="deletResource({{$serie->id}})">
                                    <i class="os-icon os-icon-trash-2"></i>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('after-script')

    <form action="" id="id-form-delete" method="POST" style="display: none">
        @method('DELETE')
        @csrf
    </form>

    <script>
        @if(Session::has('success'))
        Swal.fire(
            'Suecesso!',
            '{{Session::get('success')}}',
            'success'
        );
        @endif
        function deletResource(id) {
            Swal.fire({
                title: 'Tem certeza?',
                text: "O Recurso será deletado da base",
                icon: 'warning',
                showCancelButton: true,
                cancelButtonText: "Cancelar",
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sim Deletar'
            }).then((result) => {
                if (result.value) {
                    $("#id-form-delete").attr('action', '/series/' + id);
                    $("#form-status").val(status);
                    $("#id-form-delete").submit();
                }
            })
        }
    </script>
@endsection