routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('users', 'Admin\\UserController');
    Route::resource('revendas', 'Admin\\RevendaController');
    Route::resource('bouquets', 'Admin\\BouquetController');
    Route::resource('categories', 'Admin\\CategoryController');
    Route::resource('streams', 'Admin\\StreamController');
    Route::resource('radios', 'Admin\\RadioController');
    Route::resource('epg', 'Admin\\EpgController');
    Route::resource('hosts', 'Admin\\HostController');
    Route::resource('movies', 'Admin\\MovieController');
    Route::resource('collections', 'Admin\\CollectionController');
    Route::resource('series', 'Admin\\SerieController');
    Route::resource('seasons', 'Admin\\SeasonController');
    Route::resource('episodes', 'Admin\\EpisodeController');

    Route::get('audits', 'AuditController@index');
    Route::post('/revendas/password/?', 'Admin\\RevendaController@password');
});

Route::get('job', 'HomeController@job');
Route::get('card', 'HomeController@card');
Route::get('csv', 'HomeController@csv');
Route::get('screen', 'HomeController@homescreen');
Route::get('teste', 'HomeController@teste');

//Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

app/Http/Controllers/Admin/EpgController.php
<?php

namespace App\Http\Controllers\Admin;

use App\EpgChannel;
use App\EpgChannelItem;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class EpgController extends Controller
{
    public function index()
    {
        $canais = EpgChannel::all();
        return view('epg.index')->with(compact('canais'));
    }

    public function show($id) {
        $canais = EpgChannel::find($id);
        $progs = EpgChannelItem::where('id_canal', '=', $canais->id_canal)->get();
        return view('epg.show')->with(compact('progs'));
    }
}

resources/views/epg/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="element-wrapper">
                <div class="element-actions">
                    <a href="{{ route('bouquets.index') }}" type="button" class="btn btn-outline-secondary min-width-125 pull-right">Voltar</a>
                </div>
                <h6 class="element-header">
                    Cadastro de Bouquets
                </h6>
                <div class="element-content">
                    <div class="element-box">
                        {!!  Form::open(['route' => ['bouquets.store']]) !!}
                            @csrf

                            <x-input name="name" text="Nome" placeholder="Digite o Nome" :error="$errors"/>

                            <x-select2 name="status" text="Status" placeholder="Selecione o Status" :error="$errors"
                                       :options="array('1' => 'Ativo', '0' =>'Inativo')"/>

                            <button type="submit" class="btn btn-primary min-width-125">Cadastrar</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/epg/edit.blade.php
@extends('layouts.app')

@section('content')
    <x-message :message="Session::has('success') ? Session::get('success') : ''"/>

    <div class="row">
        <div class="col-lg-6">
            <div class="element-wrapper">
                <div class="element-actions">
                    <a href="{{ route('bouquets.index') }}" type="button" class="btn btn-outline-secondary min-width-125 pull-right">Voltar</a>
                </div>
                <h6 class="element-header">
                    Edição de Bouquets
                </h6>

                <div class="element-content">
                    <div class="element-box">
                        {!!  Form::model($bouquet, ['method' => 'PUT','route' => ['bouquets.update', $bouquet->id]]) !!}
                        @csrf

                        <x-input name="name" text="Nome" :value="$bouquet->name" placeholder="Digite o Nome" :error="$errors"/>

                        <x-select2 name="status" text="Status" placeholder="Selecione o Status" :error="$errors"
                                   :options="array('1' => 'Ativo', '0' =>'Inativo')"/>

                        <button type="submit" class="btn btn-primary min-width-125">Salvar</button>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/epg/index.blade.php
@extends('layouts.app')

@section('content')
    <x-message :message="Session::has('success') ? Session::get('success') : ''"/>

    <div class="element-wrapper">
        <h6 class="element-header">
            Listagem Epg
        </h6>

        <div class="element-content">
            <table id="dataTable1" class="table table-bordered table-striped table-vcenter js-dataTable-full">
                <thead>
                <tr>
                    <th class="text-center"></th>
                    <th class="text-center">Logo</th>
                    <th>Nome</th>
                    <th class="d-none d-sm-table-cell">Id Canal</th>
                    <th class="text-center" style="width: 15%;"></th>
                </tr>
                </thead>
                <tbody>
                    @foreach($canais as $canal)
                        <tr>
                            <td class="text-center">{{ $canal->id }}</td>
                            <td class="text-center">
                                <x-image-cell :url="$canal->url_imagem"/>
                            </td>
                            <td class="text-center">{{ $canal->nome }}</td>
                            <td class="text-center">{{ $canal->id_canal }}</td>
                            <td class="text-center">
                                <x-button :route="route('epg.show', $canal->id)" type="success" icon="os-icon-edit-32" tooltip="Visualizar Programação" />
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>


@endsection

resources/views/epg/show.blade.php
@extends('layouts.app')

@section('content')
    <x-message :message="Session::has('success') ? Session::get('success') : ''"/>

    <div class="element-wrapper">
        <h6 class="element-header">
            Listagem Epg
        </h6>

        <div class="element-content">
            <table id="dataTable1" class="table table-bordered table-striped table-vcenter js-dataTable-full">
                <thead>
                <tr>
                    <th class="text-center"></th>
                    <th class="text-center">Titulo</th>
                    <th>Programa</th>
                    <th class="d-none d-sm-table-cell">Inicio</th>
                    <th class="d-none d-sm-table-cell">Fim</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($progs as $prog)
                        <tr>
                            <td class="text-center">{{ $prog->id }}</td>
                            <td class="text-center">{{ $prog->titulo }}</td>

                            <td class="text-center">{{ $prog->id_programa }}</td>
                            <td class="text-center">{{ $prog->dh_inicio->format('H:i:s') }}</td>
                            <td class="text-center">{{ $prog->dh_fim->format('H:i:s') }}</td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>


@endsection